---
layout: single
title:  "Exception"
categories: Blog
excerpt: "exception을 하는 이유와 방법입니다"
tags: [Java, blog, coding, Exception, try-catch, throws]
toc: true
toc_sticky: true
toc_label : 목차
toc_icon: "fas fa-tasks"
author_profile: false
sidebar:
nav: "docs"


---
[Google](https://google.com){: .btn .btn--warning}


# Exception

<hr/> 


## 예외와 에러

```java

	public static void main(String[] args) {

		Exception : 코드 수정에 따라 처리할 수 있는 문제점, 예외
		Error : 코드와 무관하게 원인을 알 수 없는 문제점, 에러, 오류
		
		Scanner sc = new Scanner(System.in);
		int num;
		String input;
		
		System.out.print("정수 입력 : ");
		input = sc.nextLine();
		
		boolean isDigit = true;
		for(int i = 0; i < input.length(); i++) {
			if(input.charAt(i) < '0' || '9' < input.charAt(i)) {
				isDigit = false;
			}
		}
		
		if(input.contains(".")) {
			System.out.println(".을 포함하면 안됩니다.");
		}
		else if(isDigit == false) {
			System.out.println("문자열이 아닌 정수만 입력해야 합니다.");
		}
		else {
			num = Integer.parseInt(sc.nextLine());
			System.out.println("num : " + num);	
		}
		
		sc.close();
		
		자바에서는 예외도 클래스로 규정하여, 예외 객체가 발생하고, 이를 처리해야 합니다.
		if는 분기문인데  예외처리에 가져다쓰면 좋지않습니다. 이때 사용하는 것이 try-catch
	}

```

## try - catch

```java

	public static void main(String[] args) {
		
		Scanner sc = new Scanner(System.in);
		int num;
		
		System.out.print("정수 입력 : ");

		try {	// 예외가 발생할 수 있는 코드를 시도합니다.
			num = Integer.parseInt(sc.nextLine());	
			// return; << 리턴해도 밑에 finally는 실행합니다.
			
		} catch(NumberFormatException e) {	// 예상되는 예외가 발생하면 아래 코드를 수행합니다.
			System.out.println("정수로 변환할 수 없는 값을 입력했습니다.");
			System.out.println(e);	// e.toString()
			e.printStackTrace();  // 예외 발생 상황을 상세하게 추적하여 출력합니다. (기본값) 
			
		} finally {	// 예외 발생 여부에 상관없이 마지막에 반드시 실행합니다.
			 // finally는 함수가 무너져도 무조건 실행합니다.
			System.out.println("프로그램을 종료합니다.");
			sc.close();
		}
		
	}	//main }

```

# throws


```java

	class Timer {
	private double minute;

	public Timer(double minute) {
		this.minute = minute;
	}
	
	public void start() throws Exception {
		for
		(int i = (int)minute * 60; i != -1; i--) {
			System.out.printf("[%02d : %02d]\n", i / 60, i % 60);
			Thread.sleep(1000);
		}
	}
}

public class Ex04 {
	public static void main(String[] args) {

		throws : 현재 함수에서 발생한 예외를 caller에게 전가시킵니다.
		
		Scanner sc = new Scanner(System.in);
		double minute = 0;
		
		Timer ob = new Timer(minute);
		try {
			ob.start();
			
		} catch(Exception e) {
			e.printStackTrace();
			print : 출력, stack : 함수스택이 쌓이는 구조, trace : 경로, 추적
		}
		sc.close();
		
		프로그램의 규모가 커지고 호출하는 함수의 개수와 스택이 커지면
		일일이 처리하는 것보다 throws를 통해서 예외를 한곳에 집중시켜 처리하는 것이
		효율적입니다.
		
		프로그램마다 다른 상황을 가지는데, 규정된 예외만 처리할 수 있따면 유연성이 떨어집니다.
		따라서 직접 예외 상황을 규정하고 객체를 생성하여 던지는 throw가 필요합니다.
	}
}
	
```
